const SERVICES=[
 {sigla:'NFS',nome:'Nota Fiscal de Serviço',desc:'Emissão, consulta, correção e cancelamento de NFS-e.',types:['Emissão/consulta de NFS-e','Cancelamento de nota fiscal','Correção de nota fiscal','Dúvidas sobre NFS-e']},
 {sigla:'ALV',nome:'Alvarás e Licenciamento',desc:'Emissão, renovação e consulta de alvarás.',types:['Emissão de alvará','Renovação de alvará','Consulta de alvará']},
 {sigla:'CER',nome:'Certidões e Documentos',desc:'Certidões municipais e documentos tributários.',types:['Certidão negativa','Certidões municipais']},
 {sigla:'IPT',nome:'IPTU e Tributos Municipais',desc:'Consultas, guias e regularização de débitos.',types:['Consulta de IPTU','Segunda via de guia','Regularização de débitos']},
 {sigla:'ITB',nome:'ITBI',desc:'Atendimento e processos relacionados ao ITBI.',types:['Atendimento ITBI']},
 {sigla:'ISS',nome:'ISSQN',desc:'Atendimento ao contribuinte e regularização.',types:['Atendimento ISSQN']},
 {sigla:'CAD',nome:'Cadastro e Atualização Cadastral',desc:'Dados cadastrais, credenciamento e alterações.',types:['Atualização cadastral','Credenciamento']},
 {sigla:'GER',nome:'Atendimento Geral',desc:'Informações, processos e orientação tributária.',types:['Informações gerais']}
];
const demoUsers={
 'cidadao@exemplo.com':{senha:'123456',role:'cidadao',nome:'João da Silva'},
 '1001':{senha:'1234',role:'atendente',nome:'Maria Santos'},
 '9000':{senha:'admin',role:'admin',nome:'Administrador do Sistema'}
};
let db=JSON.parse(localStorage.getItem('atende_pvh')||'null')||{counter:42,ticket:null,queue:[],history:[],current:null};
let user=JSON.parse(localStorage.getItem('atende_user')||'null');
function save(){localStorage.setItem('atende_pvh',JSON.stringify(db));localStorage.setItem('atende_user',JSON.stringify(user))}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function shell(html){document.getElementById('app').innerHTML=html}
function home(){shell(`<section class="hero"><div class="container"><span class="badge">PROTÓTIPO ACADÊMICO</span><h1>Bem-vindo à Central de Atendimento</h1><p>Escolha o serviço, retire sua senha e acompanhe sua posição na fila de forma simples e transparente.</p><div class="actions"><button class="primary" onclick="showServices()">Escolher serviço</button><button class="secondary" onclick="login()">Entrar</button><button class="secondary" onclick="takeTicket()">Retirar uma senha</button></div></div></section><div class="container"><h2>Como funciona?</h2><div class="steps"><div class="step"><b>1. Escolha</b><p class="muted">Selecione o serviço.</p></div><div class="step"><b>2. Senha</b><p class="muted">Retire ou agende.</p></div><div class="step"><b>3. Acompanhe</b><p class="muted">Veja sua posição.</p></div><div class="step"><b>4. Compareça</b><p class="muted">Veja o guichê quando chamado.</p></div></div><div class="section"><h2>Serviços disponíveis</h2><div class="grid">${SERVICES.map((s,i)=>`<article class="card service" onclick="service(${i})"><span class="badge">${s.sigla}</span><h3>${s.nome}</h3><p class="muted">${s.desc}</p></article>`).join('')}</div></div></div>`)}
function showServices(){shell(`<div class="container"><h1>Serviços</h1><p class="muted">Escolha o assunto que deseja resolver.</p><div class="grid">${SERVICES.map((s,i)=>`<article class="card service" onclick="service(${i})"><span class="badge">${s.sigla}</span><h3>${s.nome}</h3><p class="muted">${s.desc}</p></article>`).join('')}</div></div>`)}
function service(i){const s=SERVICES[i];shell(`<div class="container"><button class="button alt" onclick="showServices()">← Voltar</button><div class="form" style="max-width:760px"><span class="badge">${s.sigla}</span><h1>${s.nome}</h1><p class="muted">${s.desc}</p><h3>Qual atendimento você precisa?</h3><div class="grid">${s.types.map((t,j)=>`<button class="card" onclick="confirmService(${i},${j})" style="text-align:left"><b>${t}</b><p class="muted">Solicitar atendimento</p></button>`).join('')}</div></div></div>`)}
function confirmService(si,ti){if(!user){login('Faça login para retirar uma senha.');return}const s=SERVICES[si],type=s.types[ti];shell(`<div class="container"><div class="form center"><span class="badge">${s.sigla}</span><h2>${type}</h2><p class="muted">Como deseja ser atendido?</p><div class="actions" style="justify-content:center"><button class="button" onclick="generateTicket(${si},${ti})">Atendimento agora</button><button class="button alt" onclick="schedule(${si},${ti})">Agendar</button></div></div></div>`)}
function generateTicket(si,ti){const s=SERVICES[si];db.counter++;const code=`${s.sigla}-${String(db.counter).padStart(3,'0')}`;const ticket={code,service:s.nome,type:s.types[ti],position:db.queue.length+1,status:'AGUARDANDO',created:new Date().toLocaleString('pt-BR'),user:user.nome};db.ticket=ticket;db.queue.push(ticket);save();toast('Senha gerada com sucesso!');showTicket()}
function showTicket(){if(!db.ticket){shell(`<div class="container center"><h1>Nenhuma senha ativa</h1><p class="muted">Você ainda não possui um atendimento ativo.</p><button class="button" onclick="showServices()">Retirar senha</button></div>`);return}const t=db.ticket;const pos=db.queue.findIndex(x=>x.code===t.code)+1;const ahead=Math.max(pos-1,0);shell(`<div class="container"><div class="card center"><span class="badge">MINHA SENHA</span><div class="ticket">${t.code}</div><h2>${t.type}</h2><span class="status ${t.status==='CHAMADO'?'ok':''}">${t.status}</span><div class="grid" style="margin-top:22px"><div class="card"><div class="stat">${pos}</div><p class="muted">Sua posição</p></div><div class="card"><div class="stat">${ahead}</div><p class="muted">Pessoas à frente</p></div><div class="card"><div class="stat">${Math.max(ahead*5,0)} min</div><p class="muted">Estimativa</p></div></div>${t.status==='CHAMADO'?`<div class="section"><h2>É a sua vez!</h2><p>Dirija-se ao <b>Guichê ${db.current?.guiche||3}</b>.</p></div>`:`<p class="muted">Acompanhe esta tela. Quando for sua vez, o sistema mostrará o guichê.</p>`}<button class="button" onclick="simulateNext()">Simular próximo atendimento</button></div></div>`)}
function simulateNext(){if(!db.queue.length){toast('Fila vazia');return}const next=db.queue.find(x=>x.status==='AGUARDANDO');if(next){next.status='CHAMADO';db.current={...next,guiche:3};if(db.ticket&&next.code===db.ticket.code)db.ticket.status='CHAMADO';save();toast(`${next.code} foi chamado!`);showTicket()}else toast('Nenhuma senha aguardando.')}
function schedule(si,ti){const s=SERVICES[si];shell(`<div class="container"><div class="form"><h2>Agendar atendimento</h2><p class="muted">${s.nome} — ${s.types[ti]}</p><div class="field"><label>Data</label><input id="date" type="date"></div><div class="field"><label>Horário</label><select id="time">${['08:00','08:30','09:00','09:30','10:00','10:30','11:00','11:30','13:00','13:30'].map(x=>`<option>${x}</option>`).join('')}</select></div><button class="button" onclick="confirmSchedule(${si},${ti})">Confirmar agendamento</button></div></div>`)}
function confirmSchedule(si,ti){const d=document.getElementById('date').value;if(!d){toast('Informe a data.');return}const protocol=`AG-${Date.now().toString().slice(-8)}`;db.history.unshift({protocol,date:d,time:document.getElementById('time').value,service:SERVICES[si].nome,type:SERVICES[si].types[ti],status:'AGENDADO'});save();shell(`<div class="container center"><div class="card"><h1>Agendamento confirmado!</h1><p>Protocolo</p><div class="ticket" style="font-size:48px">${protocol}</div><p>${d} às ${document.getElementById('time').value}</p><p>${SERVICES[si].nome} — ${SERVICES[si].types[ti]}</p><button class="button" onclick="home()">Voltar ao início</button></div></div>`)}
function login(message=''){shell(`<div class="container"><div class="form"><h1>Entrar</h1>${message?`<p class="muted">${message}</p>`:''}<div class="field"><label>Login</label><input id="login" placeholder="CPF, e-mail ou matrícula"></div><div class="field"><label>Senha</label><input id="pass" type="password" placeholder="Senha"></div><button class="button" onclick="doLogin()">Entrar</button><p class="muted">Demonstração: cidadão@exemplo.com / 123456 · atendente 1001 / 1234 · admin 9000 / admin</p></div></div>`)}
function doLogin(){const l=document.getElementById('login').value.trim(),p=document.getElementById('pass').value;const u=demoUsers[l];if(!u||u.senha!==p){toast('Login ou senha inválidos.');return}user=u;save();toast('Login realizado.');home()}
function takeTicket(){if(!user){login('Faça login para retirar uma senha.');return}showServices()}
function admin(){if(!user){login('Entre para acessar o painel.');return}const total=db.queue.length,waiting=db.queue.filter(x=>x.status==='AGUARDANDO').length,called=db.queue.filter(x=>x.status==='CHAMADO').length;shell(`<div class="container"><h1>Painel de atendimento</h1><div class="grid"><div class="card"><p class="muted">Senhas na fila</p><div class="stat">${total}</div></div><div class="card"><p class="muted">Aguardando</p><div class="stat">${waiting}</div></div><div class="card"><p class="muted">Chamadas</p><div class="stat">${called}</div></div><div class="card"><p class="muted">Atendimentos concluídos</p><div class="stat">${db.history.length}</div></div></div><div class="section"><h2>Fila</h2><table><thead><tr><th>Senha</th><th>Cidadão</th><th>Serviço</th><th>Status</th></tr></thead><tbody>${db.queue.map(t=>`<tr><td><b>${t.code}</b></td><td>${t.user}</td><td>${t.service}</td><td>${t.status}</td></tr>`).join('')||'<tr><td colspan="4">Nenhuma senha.</td></tr>'}</tbody></table></div><div class="actions"><button class="button" onclick="callNext()">Chamar próximo</button><button class="button alt" onclick="tv()">Abrir painel da TV</button></div></div>`)}
function callNext(){const next=db.queue.find(x=>x.status==='AGUARDANDO');if(!next){toast('Fila vazia.');return}next.status='CHAMADO';db.current={...next,guiche:3};if(db.ticket?.code===next.code)db.ticket.status='CHAMADO';save();toast(`${next.code} chamado no Guichê 3.`);admin()}
function tv(){const c=db.current;shell(`<div class="big-screen"><div><p style="font-size:22px;opacity:.7">ATENDE PVH · PAINEL DE CHAMADAS</p>${c?`<div class="ticket">${c.code}</div><h1>GUICHÊ ${c.guiche||3}</h1><p>${c.type}</p>`:`<h1>Aguardando próxima chamada</h1>`}<button class="button alt" onclick="home()">Voltar</button></div></div>`)}
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>({home,services:showServices,ticket:showTicket,admin}[b.dataset.page])()));document.getElementById('loginBtn').addEventListener('click',()=>user?logout():login());function logout(){user=null;save();toast('Sessão encerrada.');home()}home();
